# -*- coding: utf-8 -*-
"""capture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0Yz6PGcxzgrMlga8EizyG26R5Ap5zCM
"""

#!pip install face_recognition



"""ライブラリーのインポート"""

import sys
import face_recognition
import cv2
import numpy as np
from PIL import ImageFont, ImageDraw, Image
import glob

video_capture = cv2.VideoCapture(0)

def main():

    while True:
        # ビデオの単一フレームを取得
        _, frame = video_capture.read()



        # 結果をビデオに表示
        cv2.imshow('Video', frame)

        # ESCキーで終了
        if cv2.waitKey(1) == 27:
            break

main()

video_capture.release()
cv2.destroyAllWindows()